
---

# **2. Dockerfile**

```Dockerfile
FROM python:3.12-slim

WORKDIR /app
COPY app/ ./app/
COPY requirements.txt ./

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
